project:
  type: website 

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with Quarto - 2024"
  sidebar:
    - contents:
      - section: "Personal"
        contents:
         - text: Resume
           href: data/resume.qmd
      - section: "Teaching"
        contents:
          - section: Syllabus
            contents:
             - text: Syllabus
               href: data/syllabus.qmd
          - section: Lecture
            contents:
             - text: Lesson One
               href: data/lesson-one.qmd
             - text: Lesson Two
               href: data/lesson-two.qmd
             - text: Lesson Three
               href: data/lesson-three.qmd
             - text: Lesson Four
               href: data/lesson-four.qmd
          - section: Assignments
            contents:
             - text: Assignment One
               href: data/assignment-one.qmd
             - text: Assignment Two
               href: data/assignment-two.qmd
             - text: Assignment Three
               href: data/assignment-three.qmd
             - text: Assignment Four
               href: data/assignment-four.qmd

      - section: "Research"
        contents:
          - text: Publications
            href: data/publications.qmd
          - text: Journals
            href: data/journals.qmd
          - text: Research
            href: data/research.qmd

      - section: "Writings"
        contents:
          - text: Blog
            href: blog/index.qmd
          - text: Projects
            href: projects/index.qmd

format:
  html:
    theme: [cosmo, styles.scss]








